### ISSUE TITLE
Harvest to S3 bucket

### ISSUE THREAD

**Issue by jvanulde** [denevers/PyHarvest#13]
Ensure that harvester is posting to an S3 bucket that is accessible by the inferencing engine.

**Comment by denevers** [comment]
The bit I needed to solve here is to automate the loading of blazegraph.  the inference is done on my desktop, i can move it to docker.  I just to tie:
- start the docker from a lambda
- let the docker pull the data from s3
- push it back to s3 OR move it directly to blazegraph running in another docker

**Comment by denevers** [comment]
deployed on i-07e53386f2a48ba56i-07e53386f2a48ba56

**Comment by denevers** [comment]
I stopped the instance.. next step.. prod..

**Comment by jvanulde** [comment]
Did it work from outside?
