### ISSUE TITLE
Deploy Blazegraph SPARQL endpoint

### ISSUE THREAD

**Issue by jvanulde** [denevers/PyHarvest#2]
1. Blazegraph - deploy as container on Azure
2. Connect Blazegraph to GSIP - only available to GSIP not publicly

**Comment by denevers** [comment]
I tried https://hub.docker.com/r/lyrasis/blazegraph and it works fine

**Comment by jvanulde** [comment]
Does work. Needs to be deployed.

**Comment by jvanulde** [comment]
Done
