### ISSUE TITLE
Get harvester to read from PostGreSQL instead file

### ISSUE THREAD

**Issue by jvanulde** [denevers/PyHarvest#6]
We need the harvester to read triples from PostGreSQL so that it can send them to JENA (inference engine) and then pushed into Blazegraph.

**Comment by denevers** [comment]
done.  Although the way it's done right now, it uses a single POST to blazegraph.  won't be good for long term (but is there a long term ?) for larger files

I should either chunk it or use a shared volume between blazegraph container and use blazegraph bulk load.  This way I could push the whole thing in one shot.

The inferrencer is in NRCan GitLab https://gccode.ssc-spc.gc.ca/eric.boisvert2/gsipinferencer

**Comment by denevers** [comment]
Need to figure a way to launch the process in the container (not containerised yet)

**Comment by jvanulde** [comment]
As discussed Jan 22, 2020, we are moving this into a separate component now that we are removing the database dependency.
